[package]
name = "ss58_converter"
version = "0.1.0"
authors = ["397702186@qq.com <397702186@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "*"
hex = "0.4"
base58 = "*"